import { CompanySettings } from '../types';

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  legalName: 'Software Architec SAC',
  commercialName: 'Software Architec',
  logoUrl: '',
  logotipoUrl: '',
  logotipoLightUrl: '',
  logotipoDarkUrl: '',
  isotipoUrl: '',
  isotipoLightUrl: '',
  isotipoDarkUrl: '',
  imagotipoUrl: '',
  imagotipoLightUrl: '',
  imagotipoDarkUrl: '',
  isologoUrl: '',
  isologoLightUrl: '',
  isologoDarkUrl: '',
  ruc: '20610948215',
  address: 'Av. Javier Prado Este 4200, Santiago de Surco',
  city: 'Lima',
  country: 'Perú',
  legalRepresentative: 'Aldair Flores - Lead Software Architect',
  brandSlogan: 'Automatización comercial y software modular para empresas de alto rendimiento',
  salesPhone: '+51 987 654 321',
  salesWhatsapp: '51987654321',
  whatsappWelcomeMessage: 'Hola Software Architec, deseo cotizar una solución tecnológica para mi empresa.',
  supportPhone: '+51 987 654 322',
  salesEmail: 'contacto@softwarearchitec.com',
  supportEmail: 'soporte@softwarearchitec.com',
  businessHours: 'Lunes a Sábado: 8:30 AM - 7:00 PM (Soporte crítico 24/7)',
  bcpAccount: '191-98765432-0-12',
  bcpCci: '002-191-009876543201-55',
  bbvaAccount: '0011-0123-4567890123',
  bbvaCci: '011-123-000123456789-40',
  interbankAccount: '200-3001234567',
  interbankCci: '003-200-003001234567-88',
  bankAccountHolder: 'Software Architec SAC',
  yapePhone: '987 654 321',
  yapeHolder: 'Software Architec SAC',
  plinPhone: '987 654 321',
  plinHolder: 'Software Architec SAC',
  instagramUrl: 'https://instagram.com/softwarearchitec',
  tiktokUrl: 'https://tiktok.com/@softwarearchitec',
  linkedinUrl: 'https://linkedin.com/company/softwarearchitec',
  facebookUrl: 'https://facebook.com/softwarearchitec',
  youtubeUrl: 'https://youtube.com/@softwarearchitec',
  slaUptime: '99.9%',
  serverLatency: '<1s',
  storageType: 'Almacenamiento NVMe SSD',
  defaultDeliveryDays: '3 a 5 días hábiles',
  currencySymbol: 'S/',
  currencyCode: 'PEN',
  variashopDemoUrl: '/servicios/saas#demo-box',
};
